// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sakhoury/kube-compare-mcp/pkg/acm (interfaces: PolicyLister,ResourceInspector,ACMClientFactory)
//
// Generated by this command:
//
//	mockgen -destination=mock_acm_interfaces_test.go -package=mcpserver_test github.com/sakhoury/kube-compare-mcp/pkg/acm PolicyLister,ResourceInspector,ACMClientFactory
//

// Package mcpserver_test is a generated GoMock package.
package mcpserver_test

import (
	context "context"
	reflect "reflect"

	acm "github.com/sakhoury/kube-compare-mcp/pkg/acm"
	gomock "go.uber.org/mock/gomock"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	rest "k8s.io/client-go/rest"
)

// MockPolicyLister is a mock of PolicyLister interface.
type MockPolicyLister struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyListerMockRecorder
	isgomock struct{}
}

// MockPolicyListerMockRecorder is the mock recorder for MockPolicyLister.
type MockPolicyListerMockRecorder struct {
	mock *MockPolicyLister
}

// NewMockPolicyLister creates a new mock instance.
func NewMockPolicyLister(ctrl *gomock.Controller) *MockPolicyLister {
	mock := &MockPolicyLister{ctrl: ctrl}
	mock.recorder = &MockPolicyListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyLister) EXPECT() *MockPolicyListerMockRecorder {
	return m.recorder
}

// GetPolicy mocks base method.
func (m *MockPolicyLister) GetPolicy(ctx context.Context, name, namespace string) (*acm.PolicyDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, name, namespace)
	ret0, _ := ret[0].(*acm.PolicyDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockPolicyListerMockRecorder) GetPolicy(ctx, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockPolicyLister)(nil).GetPolicy), ctx, name, namespace)
}

// ListPolicies mocks base method.
func (m *MockPolicyLister) ListPolicies(ctx context.Context, namespace string) ([]acm.PolicySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicies", ctx, namespace)
	ret0, _ := ret[0].([]acm.PolicySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicies indicates an expected call of ListPolicies.
func (mr *MockPolicyListerMockRecorder) ListPolicies(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicies", reflect.TypeOf((*MockPolicyLister)(nil).ListPolicies), ctx, namespace)
}

// MockResourceInspector is a mock of ResourceInspector interface.
type MockResourceInspector struct {
	ctrl     *gomock.Controller
	recorder *MockResourceInspectorMockRecorder
	isgomock struct{}
}

// MockResourceInspectorMockRecorder is the mock recorder for MockResourceInspector.
type MockResourceInspectorMockRecorder struct {
	mock *MockResourceInspector
}

// NewMockResourceInspector creates a new mock instance.
func NewMockResourceInspector(ctrl *gomock.Controller) *MockResourceInspector {
	mock := &MockResourceInspector{ctrl: ctrl}
	mock.recorder = &MockResourceInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceInspector) EXPECT() *MockResourceInspectorMockRecorder {
	return m.recorder
}

// CheckAccess mocks base method.
func (m *MockResourceInspector) CheckAccess(ctx context.Context, verb string, gvr schema.GroupVersionResource, namespace string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccess", ctx, verb, gvr, namespace)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccess indicates an expected call of CheckAccess.
func (mr *MockResourceInspectorMockRecorder) CheckAccess(ctx, verb, gvr, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccess", reflect.TypeOf((*MockResourceInspector)(nil).CheckAccess), ctx, verb, gvr, namespace)
}

// DryRunPatch mocks base method.
func (m *MockResourceInspector) DryRunPatch(ctx context.Context, gvr schema.GroupVersionResource, name, namespace string, patch []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRunPatch", ctx, gvr, name, namespace, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DryRunPatch indicates an expected call of DryRunPatch.
func (mr *MockResourceInspectorMockRecorder) DryRunPatch(ctx, gvr, name, namespace, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRunPatch", reflect.TypeOf((*MockResourceInspector)(nil).DryRunPatch), ctx, gvr, name, namespace, patch)
}

// GetResource mocks base method.
func (m *MockResourceInspector) GetResource(ctx context.Context, gvr schema.GroupVersionResource, name, namespace string) (*unstructured.Unstructured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResource", ctx, gvr, name, namespace)
	ret0, _ := ret[0].(*unstructured.Unstructured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResource indicates an expected call of GetResource.
func (mr *MockResourceInspectorMockRecorder) GetResource(ctx, gvr, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResource", reflect.TypeOf((*MockResourceInspector)(nil).GetResource), ctx, gvr, name, namespace)
}

// ListEvents mocks base method.
func (m *MockResourceInspector) ListEvents(ctx context.Context, name, namespace, kind string) ([]acm.EventInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, name, namespace, kind)
	ret0, _ := ret[0].([]acm.EventInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockResourceInspectorMockRecorder) ListEvents(ctx, name, namespace, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockResourceInspector)(nil).ListEvents), ctx, name, namespace, kind)
}

// ListMutatingWebhooks mocks base method.
func (m *MockResourceInspector) ListMutatingWebhooks(ctx context.Context) ([]acm.WebhookInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMutatingWebhooks", ctx)
	ret0, _ := ret[0].([]acm.WebhookInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMutatingWebhooks indicates an expected call of ListMutatingWebhooks.
func (mr *MockResourceInspectorMockRecorder) ListMutatingWebhooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMutatingWebhooks", reflect.TypeOf((*MockResourceInspector)(nil).ListMutatingWebhooks), ctx)
}

// ListResources mocks base method.
func (m *MockResourceInspector) ListResources(ctx context.Context, gvr schema.GroupVersionResource, namespace string) ([]unstructured.Unstructured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResources", ctx, gvr, namespace)
	ret0, _ := ret[0].([]unstructured.Unstructured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockResourceInspectorMockRecorder) ListResources(ctx, gvr, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockResourceInspector)(nil).ListResources), ctx, gvr, namespace)
}

// ListValidatingWebhooks mocks base method.
func (m *MockResourceInspector) ListValidatingWebhooks(ctx context.Context) ([]acm.WebhookInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListValidatingWebhooks", ctx)
	ret0, _ := ret[0].([]acm.WebhookInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListValidatingWebhooks indicates an expected call of ListValidatingWebhooks.
func (mr *MockResourceInspectorMockRecorder) ListValidatingWebhooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListValidatingWebhooks", reflect.TypeOf((*MockResourceInspector)(nil).ListValidatingWebhooks), ctx)
}

// MockACMClientFactory is a mock of ACMClientFactory interface.
type MockACMClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockACMClientFactoryMockRecorder
	isgomock struct{}
}

// MockACMClientFactoryMockRecorder is the mock recorder for MockACMClientFactory.
type MockACMClientFactoryMockRecorder struct {
	mock *MockACMClientFactory
}

// NewMockACMClientFactory creates a new mock instance.
func NewMockACMClientFactory(ctrl *gomock.Controller) *MockACMClientFactory {
	mock := &MockACMClientFactory{ctrl: ctrl}
	mock.recorder = &MockACMClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockACMClientFactory) EXPECT() *MockACMClientFactoryMockRecorder {
	return m.recorder
}

// NewPolicyLister mocks base method.
func (m *MockACMClientFactory) NewPolicyLister(config *rest.Config) (acm.PolicyLister, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPolicyLister", config)
	ret0, _ := ret[0].(acm.PolicyLister)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPolicyLister indicates an expected call of NewPolicyLister.
func (mr *MockACMClientFactoryMockRecorder) NewPolicyLister(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPolicyLister", reflect.TypeOf((*MockACMClientFactory)(nil).NewPolicyLister), config)
}

// NewResourceInspector mocks base method.
func (m *MockACMClientFactory) NewResourceInspector(config *rest.Config) (acm.ResourceInspector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewResourceInspector", config)
	ret0, _ := ret[0].(acm.ResourceInspector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewResourceInspector indicates an expected call of NewResourceInspector.
func (mr *MockACMClientFactoryMockRecorder) NewResourceInspector(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewResourceInspector", reflect.TypeOf((*MockACMClientFactory)(nil).NewResourceInspector), config)
}
