// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sakhoury/kube-compare-mcp/pkg/mcpserver (interfaces: RegistryClient,ClusterClient,ClusterClientFactory,HTTPDoer)
//
// Generated by this command:
//
//	mockgen -destination=mock_interfaces_test.go -package=mcpserver_test github.com/sakhoury/kube-compare-mcp/pkg/mcpserver RegistryClient,ClusterClient,ClusterClientFactory,HTTPDoer
//

// Package mcpserver_test is a generated GoMock package.
package mcpserver_test

import (
	context "context"
	http "net/http"
	reflect "reflect"

	mcpserver "github.com/sakhoury/kube-compare-mcp/pkg/mcpserver"
	gomock "go.uber.org/mock/gomock"
	rest "k8s.io/client-go/rest"
)

// MockRegistryClient is a mock of RegistryClient interface.
type MockRegistryClient struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryClientMockRecorder
	isgomock struct{}
}

// MockRegistryClientMockRecorder is the mock recorder for MockRegistryClient.
type MockRegistryClientMockRecorder struct {
	mock *MockRegistryClient
}

// NewMockRegistryClient creates a new mock instance.
func NewMockRegistryClient(ctrl *gomock.Controller) *MockRegistryClient {
	mock := &MockRegistryClient{ctrl: ctrl}
	mock.recorder = &MockRegistryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryClient) EXPECT() *MockRegistryClientMockRecorder {
	return m.recorder
}

// HeadImage mocks base method.
func (m *MockRegistryClient) HeadImage(ctx context.Context, imageRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadImage", ctx, imageRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// HeadImage indicates an expected call of HeadImage.
func (mr *MockRegistryClientMockRecorder) HeadImage(ctx, imageRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadImage", reflect.TypeOf((*MockRegistryClient)(nil).HeadImage), ctx, imageRef)
}

// ListTags mocks base method.
func (m *MockRegistryClient) ListTags(ctx context.Context, repo string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx, repo)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockRegistryClientMockRecorder) ListTags(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockRegistryClient)(nil).ListTags), ctx, repo)
}

// MockClusterClient is a mock of ClusterClient interface.
type MockClusterClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientMockRecorder
	isgomock struct{}
}

// MockClusterClientMockRecorder is the mock recorder for MockClusterClient.
type MockClusterClientMockRecorder struct {
	mock *MockClusterClient
}

// NewMockClusterClient creates a new mock instance.
func NewMockClusterClient(ctrl *gomock.Controller) *MockClusterClient {
	mock := &MockClusterClient{ctrl: ctrl}
	mock.recorder = &MockClusterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClient) EXPECT() *MockClusterClientMockRecorder {
	return m.recorder
}

// GetClusterVersion mocks base method.
func (m *MockClusterClient) GetClusterVersion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterVersion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterVersion indicates an expected call of GetClusterVersion.
func (mr *MockClusterClientMockRecorder) GetClusterVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterVersion", reflect.TypeOf((*MockClusterClient)(nil).GetClusterVersion), ctx)
}

// MockClusterClientFactory is a mock of ClusterClientFactory interface.
type MockClusterClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientFactoryMockRecorder
	isgomock struct{}
}

// MockClusterClientFactoryMockRecorder is the mock recorder for MockClusterClientFactory.
type MockClusterClientFactoryMockRecorder struct {
	mock *MockClusterClientFactory
}

// NewMockClusterClientFactory creates a new mock instance.
func NewMockClusterClientFactory(ctrl *gomock.Controller) *MockClusterClientFactory {
	mock := &MockClusterClientFactory{ctrl: ctrl}
	mock.recorder = &MockClusterClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClientFactory) EXPECT() *MockClusterClientFactoryMockRecorder {
	return m.recorder
}

// NewClient mocks base method.
func (m *MockClusterClientFactory) NewClient(config *rest.Config) (mcpserver.ClusterClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", config)
	ret0, _ := ret[0].(mcpserver.ClusterClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient.
func (mr *MockClusterClientFactoryMockRecorder) NewClient(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockClusterClientFactory)(nil).NewClient), config)
}

// MockHTTPDoer is a mock of HTTPDoer interface.
type MockHTTPDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPDoerMockRecorder
	isgomock struct{}
}

// MockHTTPDoerMockRecorder is the mock recorder for MockHTTPDoer.
type MockHTTPDoerMockRecorder struct {
	mock *MockHTTPDoer
}

// NewMockHTTPDoer creates a new mock instance.
func NewMockHTTPDoer(ctrl *gomock.Controller) *MockHTTPDoer {
	mock := &MockHTTPDoer{ctrl: ctrl}
	mock.recorder = &MockHTTPDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPDoer) EXPECT() *MockHTTPDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPDoer)(nil).Do), req)
}
