// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sakhoury/kube-compare-mcp/pkg/acm (interfaces: ResourceInspector)
//
// Generated by this command:
//
//	mockgen -destination=mock_interfaces_test.go -package=k8s_test github.com/sakhoury/kube-compare-mcp/pkg/acm ResourceInspector
//

// Package k8s_test is a generated GoMock package.
package k8s_test

import (
	context "context"
	reflect "reflect"

	acm "github.com/sakhoury/kube-compare-mcp/pkg/acm"
	gomock "go.uber.org/mock/gomock"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// MockResourceInspector is a mock of ResourceInspector interface.
type MockResourceInspector struct {
	ctrl     *gomock.Controller
	recorder *MockResourceInspectorMockRecorder
	isgomock struct{}
}

// MockResourceInspectorMockRecorder is the mock recorder for MockResourceInspector.
type MockResourceInspectorMockRecorder struct {
	mock *MockResourceInspector
}

// NewMockResourceInspector creates a new mock instance.
func NewMockResourceInspector(ctrl *gomock.Controller) *MockResourceInspector {
	mock := &MockResourceInspector{ctrl: ctrl}
	mock.recorder = &MockResourceInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceInspector) EXPECT() *MockResourceInspectorMockRecorder {
	return m.recorder
}

// CheckAccess mocks base method.
func (m *MockResourceInspector) CheckAccess(ctx context.Context, verb string, gvr schema.GroupVersionResource, namespace string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccess", ctx, verb, gvr, namespace)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccess indicates an expected call of CheckAccess.
func (mr *MockResourceInspectorMockRecorder) CheckAccess(ctx, verb, gvr, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccess", reflect.TypeOf((*MockResourceInspector)(nil).CheckAccess), ctx, verb, gvr, namespace)
}

// DryRunPatch mocks base method.
func (m *MockResourceInspector) DryRunPatch(ctx context.Context, gvr schema.GroupVersionResource, name, namespace string, patch []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRunPatch", ctx, gvr, name, namespace, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DryRunPatch indicates an expected call of DryRunPatch.
func (mr *MockResourceInspectorMockRecorder) DryRunPatch(ctx, gvr, name, namespace, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRunPatch", reflect.TypeOf((*MockResourceInspector)(nil).DryRunPatch), ctx, gvr, name, namespace, patch)
}

// GetResource mocks base method.
func (m *MockResourceInspector) GetResource(ctx context.Context, gvr schema.GroupVersionResource, name, namespace string) (*unstructured.Unstructured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResource", ctx, gvr, name, namespace)
	ret0, _ := ret[0].(*unstructured.Unstructured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResource indicates an expected call of GetResource.
func (mr *MockResourceInspectorMockRecorder) GetResource(ctx, gvr, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResource", reflect.TypeOf((*MockResourceInspector)(nil).GetResource), ctx, gvr, name, namespace)
}

// ListEvents mocks base method.
func (m *MockResourceInspector) ListEvents(ctx context.Context, name, namespace, kind string) ([]acm.EventInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, name, namespace, kind)
	ret0, _ := ret[0].([]acm.EventInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockResourceInspectorMockRecorder) ListEvents(ctx, name, namespace, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockResourceInspector)(nil).ListEvents), ctx, name, namespace, kind)
}

// ListMutatingWebhooks mocks base method.
func (m *MockResourceInspector) ListMutatingWebhooks(ctx context.Context) ([]acm.WebhookInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMutatingWebhooks", ctx)
	ret0, _ := ret[0].([]acm.WebhookInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMutatingWebhooks indicates an expected call of ListMutatingWebhooks.
func (mr *MockResourceInspectorMockRecorder) ListMutatingWebhooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMutatingWebhooks", reflect.TypeOf((*MockResourceInspector)(nil).ListMutatingWebhooks), ctx)
}

// ListResources mocks base method.
func (m *MockResourceInspector) ListResources(ctx context.Context, gvr schema.GroupVersionResource, namespace string) ([]unstructured.Unstructured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResources", ctx, gvr, namespace)
	ret0, _ := ret[0].([]unstructured.Unstructured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockResourceInspectorMockRecorder) ListResources(ctx, gvr, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockResourceInspector)(nil).ListResources), ctx, gvr, namespace)
}

// ListValidatingWebhooks mocks base method.
func (m *MockResourceInspector) ListValidatingWebhooks(ctx context.Context) ([]acm.WebhookInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListValidatingWebhooks", ctx)
	ret0, _ := ret[0].([]acm.WebhookInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListValidatingWebhooks indicates an expected call of ListValidatingWebhooks.
func (mr *MockResourceInspectorMockRecorder) ListValidatingWebhooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListValidatingWebhooks", reflect.TypeOf((*MockResourceInspector)(nil).ListValidatingWebhooks), ctx)
}
